// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/(auth)/_layout.tsx";
import * as $1 from "./routes/(auth)/login.tsx";
import * as $2 from "./routes/(auth)/logout.tsx";
import * as $3 from "./routes/(auth)/signup.tsx";
import * as $4 from "./routes/(protected)/_middleware.ts";
import * as $5 from "./routes/(protected)/secret.tsx";
import * as $6 from "./routes/_404.tsx";
import * as $7 from "./routes/_app.tsx";
import * as $8 from "./routes/_layout.tsx";
import * as $9 from "./routes/api/joke.ts";
import * as $10 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/(auth)/_layout.tsx": $0,
    "./routes/(auth)/login.tsx": $1,
    "./routes/(auth)/logout.tsx": $2,
    "./routes/(auth)/signup.tsx": $3,
    "./routes/(protected)/_middleware.ts": $4,
    "./routes/(protected)/secret.tsx": $5,
    "./routes/_404.tsx": $6,
    "./routes/_app.tsx": $7,
    "./routes/_layout.tsx": $8,
    "./routes/api/joke.ts": $9,
    "./routes/index.tsx": $10,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
